"""Add user_id to candidates for automatic account creation

Revision ID: bc8ead3a715f
Revises: 
Create Date: 2026-04-27 14:03:43.989152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8ead3a715f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_candidates_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_candidates_user_id', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_candidates_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_candidates_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
